---
spring:
  profiles: local
  main.allow-bean-definition-overriding: true
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

  h2.console:
    enabled: true
    path: /h2-console


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "cscscs"
  jpa.hibernate.ddl-auto: create-drop
#  jpa.hibernate.ddl-auto: update

server:
  port: 8080

---
# General Informations
spring:
  profiles:
    active: local
  application:
    name: TacOTac
